
GET http://localhost:8000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQwNTBlZDQyNTAyYjcyNmQ1ZWFjMzAxIiwiaWF0IjoxNjc4MDUzMDc2fQ.ii-8q4pLzP63TmKcPDQfkK2Ch2SAE2u98Qn3iFvja5w

###

POST http://localhost:8000/tasks/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQwNTBlZDQyNTAyYjcyNmQ1ZWFjMzAxIiwiaWF0IjoxNjc4MDUzMDc2fQ.ii-8q4pLzP63TmKcPDQfkK2Ch2SAE2u98Qn3iFvja5w

{
    "description": "Walk home", 
    "ends": "2023-03-10T17:02:00.000Z", 
    "completed": "false"
}

###

PUT http://localhost:8000/tasks/update/?id=6404d2d49cc5a8bada99a25a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQwNTBlZDQyNTAyYjcyNmQ1ZWFjMzAxIiwiaWF0IjoxNjc4MDUzMDc2fQ.ii-8q4pLzP63TmKcPDQfkK2Ch2SAE2u98Qn3iFvja5w

{
    "description": "Wake up your fat", 
    "ends": "2023-03-10T17:02:00.000Z", 
    "completed": "false"
}

###

DELETE http://localhost:8000/tasks/?id=6404d2d49cc5a8bada99a25a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQwNTBlZDQyNTAyYjcyNmQ1ZWFjMzAxIiwiaWF0IjoxNjc4MDUzMDc2fQ.ii-8q4pLzP63TmKcPDQfkK2Ch2SAE2u98Qn3iFvja5w

